# Generated by Django 4.0.2 on 2022-02-16 22:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeTable', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hold_class',
            name='room',
        ),
        migrations.RemoveField(
            model_name='hold_class',
            name='time',
        ),
        migrations.AlterField(
            model_name='course',
            name='unit',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
